#!/usr/bin/env python3
"""Make a plan store readable again by a build from before `P1-FS-006(b)`.

`P1-FS-006(b)` widened `FrozenSortAction.expected_size_bytes` to `int | None`,
so a plan written after it can contain `null` where every earlier build requires
an integer. That direction is safe by design: `PlanStore.load` validates the
frozen plan and, on failure, quarantines the file and raises a typed
`InvalidPlanStoreError`. An older build therefore *refuses* such a plan — it
never misreads one.

Refusing is correct but untidy: downgrade and every affected plan is quarantined
one at a time, as a fresh error, at the moment the user tries to execute it.
This script performs that step deliberately and in advance instead.

**It is the compensating migration for a forward-only change, and it is
deliberately conservative:**

* it only ever touches plans that an older build genuinely cannot read — a plan
  whose sizes are all integers is left exactly where it is;
* it copies each file into a timestamped backup directory before removing it,
  so nothing is destroyed;
* it does nothing at all without `--apply`.

A reviewed plan is a 24-hour cache of a review (`EXECUTION_WINDOW`), not user
data, and it is regenerated by running the preview again. That is what bounds
the cost of this migration to re-reviewing at most one day of work.

    python scripts/downgrade_plan_store.py --root <state-dir>/plans
    python scripts/downgrade_plan_store.py --root <state-dir>/plans --apply
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PLAN_SUFFIX = ".plan.json"
BACKUP_PREFIX = "pre-downgrade-"


def has_unknown_size(envelope: Any) -> bool:
    """True when any frozen action carries a size an older build cannot parse.

    Reads the envelope structurally rather than through the Pydantic model, so
    the script keeps working when run against a build whose model has already
    been reverted — which is exactly the situation it exists for.
    """
    if not isinstance(envelope, dict):
        return False
    plan = envelope.get("frozen_plan")
    if not isinstance(plan, dict):
        return False
    actions = plan.get("actions")
    if not isinstance(actions, list):
        return False
    return any(
        isinstance(action, dict) and action.get("expected_size_bytes", 0) is None
        for action in actions
    )


def affected_plans(root: Path) -> list[Path]:
    found: list[Path] = []
    for path in sorted(root.glob(f"*{PLAN_SUFFIX}")):
        try:
            envelope = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            # Unreadable already, and not something this migration introduced.
            continue
        if has_unknown_size(envelope):
            found.append(path)
    return found


def run(root: Path, *, apply: bool) -> int:
    if not root.is_dir():
        print(f"no plan store at {root}; nothing to do")
        return 0

    affected = affected_plans(root)
    if not affected:
        print(f"{root}: no plans carry an unknown size; an older build can read them all")
        return 0

    print(f"{root}: {len(affected)} plan(s) an older build cannot read:")
    for path in affected:
        print(f"  {path.name}")

    if not apply:
        print("\ndry run — pass --apply to back these up and remove them")
        return 0

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    backup = root / f"{BACKUP_PREFIX}{stamp}"
    backup.mkdir(parents=True, exist_ok=True)
    for path in affected:
        shutil.copy2(path, backup / path.name)
        path.unlink()

    print(f"\nbacked up {len(affected)} plan(s) to {backup} and removed them")
    print("run the preview again to produce plans this build can execute")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True, help="the plan store directory")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="actually back up and remove; without it nothing is written",
    )
    args = parser.parse_args(argv)
    return run(args.root, apply=args.apply)


if __name__ == "__main__":
    sys.exit(main())
