"""Reviewed plans, persisted, so a live run always has one to point at.

A frozen plan is what makes a mutating run *reviewed*: it is the exact set of
consequences the user was shown and agreed to. It lived in a dictionary on
`PreviewService`, which meant a backend restart silently discarded every plan —
and the sort route treated `plan_id` as optional, so the next live run simply
proceeded without one. Together those made "reviewed" a property the product
hoped for rather than one it enforced.

The envelope is versioned because it is now an on-disk format other builds will
read:

    {"format_version": 1, "plan_id": ..., "created_at": ..., "expires_at": ...,
     "frozen_plan": {...}}

Three refusals, each typed, because "this plan cannot be used" and "there is no
plan" must never be answered the same way:

* `PlanExpiredError` — past its 24-hour execution window. The file is kept for a
  seven-day diagnostic window so a user asking "what happened to my plan" gets
  an answer rather than a shrug.
* `InvalidPlanStoreError` — truncated, corrupt, or a leftover temporary file.
  Quarantined rather than deleted; a plan that failed to parse is evidence.
* `UnsupportedPlanStoreVersionError` — written by a newer build. Refused
  loudly. A forward-incompatible envelope read leniently is how a plan from a
  version that understood more consequences gets executed by one that
  understands fewer.

Writes are atomic: temp file, flush, `fsync`, `rename`, then `fsync` of the
directory. A half-written plan is never a readable one.
"""

from __future__ import annotations

import json
import os
import shutil
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Final

from app.core.integrity import utc_now
from app.core.logging_config import get_logger
from app.core.sort_plan import FrozenSortPlan

logger = get_logger(__name__)

#: Bumped only for an incompatible envelope change. A new *field* that older
#: builds may ignore does not need it; a changed meaning does.
PLAN_STORE_FORMAT_VERSION: Final = 1

PLAN_DIRECTORY_NAME: Final = "plans"
QUARANTINE_DIRECTORY_NAME: Final = ".unreadable"
PLAN_SUFFIX: Final = ".plan.json"
TEMP_SUFFIX: Final = ".plan.tmp"

#: How long a reviewed plan may be executed. Long enough to review properly,
#: short enough that the filesystem it describes has probably not moved on.
EXECUTION_WINDOW = timedelta(hours=24)
#: How long an expired plan is still readable for diagnostics.
DIAGNOSTIC_RETENTION = timedelta(days=7)


class PlanStoreError(RuntimeError):
    """A stored plan could not be produced. Never means 'proceed anyway'."""


class PlanExpiredError(PlanStoreError):
    """The plan is real and readable, but past its execution window."""


class InvalidPlanStoreError(PlanStoreError):
    """The envelope could not be parsed, so its consequences are unknown."""


class UnsupportedPlanStoreVersionError(PlanStoreError):
    """A newer build wrote this. Refuse rather than guess at its meaning."""


@dataclass(frozen=True)
class StoredPlan:
    """A plan and the two timestamps that decide whether it may run."""

    plan: FrozenSortPlan
    created_at: datetime
    expires_at: datetime

    def is_expired(self, *, now: datetime | None = None) -> bool:
        return (now or utc_now()) >= self.expires_at

    def is_purgeable(self, *, now: datetime | None = None) -> bool:
        """Past even the diagnostic window, so nothing is lost by removing it."""
        return (now or utc_now()) >= self.expires_at + DIAGNOSTIC_RETENTION


def _parse_timestamp(value: Any, field: str) -> datetime:
    if not isinstance(value, str):
        raise InvalidPlanStoreError(f"{field} is missing or not a string")
    try:
        return datetime.fromisoformat(value)
    except ValueError as exc:
        raise InvalidPlanStoreError(f"{field} is not a valid timestamp: {value!r}") from exc


class PlanStore:
    """Durable home for reviewed plans, beside the journals they authorise."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.quarantine_root = root / QUARANTINE_DIRECTORY_NAME

    def path_for(self, plan_id: str) -> Path:
        # `plan_id` is generated by `build_frozen_sort_plan`, but it reaches
        # here from a request body, so it never becomes a path segment
        # unchecked.
        if not plan_id or "/" in plan_id or "\\" in plan_id or plan_id.startswith("."):
            raise InvalidPlanStoreError(f"refusing to treat {plan_id!r} as a plan identifier")
        return self.root / f"{plan_id}{PLAN_SUFFIX}"

    def save(self, plan: FrozenSortPlan, *, now: datetime | None = None) -> StoredPlan:
        """Write a reviewed plan atomically, and return what was written."""
        created_at = now or utc_now()
        stored = StoredPlan(
            plan=plan,
            created_at=created_at,
            expires_at=created_at + EXECUTION_WINDOW,
        )
        envelope = {
            "format_version": PLAN_STORE_FORMAT_VERSION,
            "plan_id": plan.plan_id,
            "created_at": stored.created_at.isoformat(),
            "expires_at": stored.expires_at.isoformat(),
            "frozen_plan": plan.model_dump(mode="json"),
        }

        self.root.mkdir(parents=True, exist_ok=True)
        target = self.path_for(plan.plan_id)
        temporary = target.with_suffix("").with_suffix(TEMP_SUFFIX)
        payload = json.dumps(envelope, ensure_ascii=False, indent=2)
        try:
            with temporary.open("w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, target)
            # The rename is only durable once the *directory* is synced.
            directory = os.open(self.root, os.O_RDONLY)
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
        except OSError as exc:
            temporary.unlink(missing_ok=True)
            raise PlanStoreError(f"Could not persist the reviewed plan: {exc}") from exc
        return stored

    def load(self, plan_id: str, *, now: datetime | None = None) -> StoredPlan:
        """Return an executable plan, or raise a typed refusal saying why not."""
        path = self.path_for(plan_id)
        if not path.is_file():
            raise InvalidPlanStoreError(f"no stored plan for {plan_id}")

        try:
            raw = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise InvalidPlanStoreError(f"stored plan {plan_id} is unreadable: {exc}") from exc

        try:
            envelope = json.loads(raw)
        except json.JSONDecodeError as exc:
            self._quarantine(path, f"unparseable JSON: {exc}")
            raise InvalidPlanStoreError(f"stored plan {plan_id} is corrupt") from exc
        if not isinstance(envelope, dict):
            self._quarantine(path, "envelope is not an object")
            raise InvalidPlanStoreError(f"stored plan {plan_id} is not an envelope")

        version = envelope.get("format_version")
        if version != PLAN_STORE_FORMAT_VERSION:
            if isinstance(version, int) and version > PLAN_STORE_FORMAT_VERSION:
                raise UnsupportedPlanStoreVersionError(
                    f"stored plan {plan_id} uses format version {version}; this build "
                    f"understands {PLAN_STORE_FORMAT_VERSION}. Generate the preview again."
                )
            self._quarantine(path, f"unusable format_version {version!r}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} has an unusable format_version: {version!r}"
            )

        created_at = _parse_timestamp(envelope.get("created_at"), "created_at")
        expires_at = _parse_timestamp(envelope.get("expires_at"), "expires_at")
        try:
            plan = FrozenSortPlan.model_validate(envelope["frozen_plan"])
        except (KeyError, ValueError) as exc:
            self._quarantine(path, f"frozen_plan did not validate: {exc}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} does not contain a valid plan"
            ) from exc

        if plan.plan_id != plan_id:
            self._quarantine(path, f"envelope names {plan_id} but holds {plan.plan_id}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} identifies itself as {plan.plan_id}"
            )

        stored = StoredPlan(plan=plan, created_at=created_at, expires_at=expires_at)
        if stored.is_expired(now=now):
            raise PlanExpiredError(
                f"the reviewed plan expired at {expires_at.isoformat()}; "
                "generate and review a new preview."
            )
        return stored

    def purge_expired(self, *, now: datetime | None = None) -> tuple[str, ...]:
        """Remove plans past even the diagnostic window. Explicit, never implicit.

        A `start` never calls this: silently discarding a plan the user is about
        to name would turn an expiry into a "no such plan", which is precisely
        the confusion the typed errors exist to prevent.
        """
        if not self.root.is_dir():
            return ()
        removed: list[str] = []
        for path in sorted(self.root.glob(f"*{PLAN_SUFFIX}")):
            plan_id = path.name[: -len(PLAN_SUFFIX)]
            try:
                envelope = json.loads(path.read_text(encoding="utf-8"))
                expires_at = _parse_timestamp(envelope.get("expires_at"), "expires_at")
            except (OSError, ValueError, json.JSONDecodeError, InvalidPlanStoreError):
                continue
            if (now or utc_now()) >= expires_at + DIAGNOSTIC_RETENTION:
                path.unlink(missing_ok=True)
                removed.append(plan_id)
        return tuple(removed)

    def _quarantine(self, path: Path, reason: str) -> None:
        """Move an unreadable plan aside. It is evidence, not litter."""
        try:
            self.quarantine_root.mkdir(parents=True, exist_ok=True)
            shutil.move(str(path), str(self.quarantine_root / path.name))
        except OSError:  # pragma: no cover - best effort, never the caller's problem
            logger.warning("plan_store.quarantine_failed", path=str(path), reason=reason)
            return
        logger.warning("plan_store.quarantined", path=str(path), reason=reason)


def store_for_state_root(state_root: Path) -> PlanStore:
    """Plans live beside the journals that record acting on them."""
    return PlanStore(state_root / PLAN_DIRECTORY_NAME)
