"""Reviewed plans, persisted, so a live run always has one to point at.

A frozen plan is what makes a mutating run *reviewed*: it is the exact set of
consequences the user was shown and agreed to. It lived in a dictionary on
`PreviewService`, which meant a backend restart silently discarded every plan —
and the sort route treated `plan_id` as optional, so the next live run simply
proceeded without one. Together those made "reviewed" a property the product
hoped for rather than one it enforced.

The envelope is versioned because it is now an on-disk format other builds will
read:

    {"format_version": 1, "plan_id": ..., "created_at": ..., "expires_at": ...,
     "frozen_plan": {...}, "preview_result": {...}}

The Review snapshot is additive: an older envelope remains executable, but
cannot claim restart continuity and the recovery route asks for a new preview.
Frequently changing Review decisions and view state live in a separate atomic
sidecar so one click never rewrites the complete frozen plan and snapshot.

Three refusals, each typed, because "this plan cannot be used" and "there is no
plan" must never be answered the same way:

* `PlanExpiredError` — past its 24-hour execution window. The file is kept for a
  seven-day diagnostic window so a user asking "what happened to my plan" gets
  an answer rather than a shrug.
* `InvalidPlanStoreError` — truncated, corrupt, or a leftover temporary file.
  Quarantined rather than deleted; a plan that failed to parse is evidence.
* `UnsupportedPlanStoreVersionError` — written by a newer build. Refused
  loudly. A forward-incompatible envelope read leniently is how a plan from a
  version that understood more consequences gets executed by one that
  understands fewer.

Writes are atomic: temp file, flush, `fsync`, `rename`, then `fsync` of the
directory. A half-written plan is never a readable one.
"""

from __future__ import annotations

import json
import os
import shutil
import threading
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Final

from app.core.integrity import utc_now
from app.core.logging_config import get_logger
from app.core.sort_plan import FrozenSortPlan

logger = get_logger(__name__)

#: Bumped only for an incompatible envelope change. A new *field* that older
#: builds may ignore does not need it; a changed meaning does.
PLAN_STORE_FORMAT_VERSION: Final = 1

PLAN_DIRECTORY_NAME: Final = "plans"
QUARANTINE_DIRECTORY_NAME: Final = ".unreadable"
PLAN_SUFFIX: Final = ".plan.json"
REVIEW_SUFFIX: Final = ".review.json"
TEMP_SUFFIX: Final = ".plan.tmp"

#: How long a reviewed plan may be executed. Long enough to review properly,
#: short enough that the filesystem it describes has probably not moved on.
EXECUTION_WINDOW = timedelta(hours=24)
#: How long an expired plan is still readable for diagnostics.
DIAGNOSTIC_RETENTION = timedelta(days=7)


class PlanStoreError(RuntimeError):
    """A stored plan could not be produced. Never means 'proceed anyway'."""


class PlanExpiredError(PlanStoreError):
    """The plan is real and readable, but past its execution window."""


class InvalidPlanStoreError(PlanStoreError):
    """The envelope could not be parsed, so its consequences are unknown."""


class UnsupportedPlanStoreVersionError(PlanStoreError):
    """A newer build wrote this. Refuse rather than guess at its meaning."""


@dataclass(frozen=True)
class StoredPlan:
    """A plan and the two timestamps that decide whether it may run."""

    plan: FrozenSortPlan
    created_at: datetime
    expires_at: datetime
    preview_result: dict[str, Any] | None = None
    review_state: dict[str, Any] | None = None

    def is_expired(self, *, now: datetime | None = None) -> bool:
        return (now or utc_now()) >= self.expires_at

    def is_purgeable(self, *, now: datetime | None = None) -> bool:
        """Past even the diagnostic window, so nothing is lost by removing it."""
        return (now or utc_now()) >= self.expires_at + DIAGNOSTIC_RETENTION


def _parse_timestamp(value: Any, field: str) -> datetime:
    if not isinstance(value, str):
        raise InvalidPlanStoreError(f"{field} is missing or not a string")
    try:
        return datetime.fromisoformat(value)
    except ValueError as exc:
        raise InvalidPlanStoreError(f"{field} is not a valid timestamp: {value!r}") from exc


class PlanStore:
    """Durable home for reviewed plans, beside the journals they authorise."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.quarantine_root = root / QUARANTINE_DIRECTORY_NAME
        self._write_lock = threading.RLock()
        self._known_plans: dict[str, tuple[str, datetime]] = {}

    def path_for(self, plan_id: str) -> Path:
        # `plan_id` is generated by `build_frozen_sort_plan`, but it reaches
        # here from a request body, so it never becomes a path segment
        # unchecked.
        if not plan_id or "/" in plan_id or "\\" in plan_id or plan_id.startswith("."):
            raise InvalidPlanStoreError(f"refusing to treat {plan_id!r} as a plan identifier")
        return self.root / f"{plan_id}{PLAN_SUFFIX}"

    def review_path_for(self, plan_id: str) -> Path:
        """The small, replaceable state sidecar for one validated plan id."""
        self.path_for(plan_id)
        return self.root / f"{plan_id}{REVIEW_SUFFIX}"

    def save(
        self,
        plan: FrozenSortPlan,
        *,
        now: datetime | None = None,
        preview_result: dict[str, Any] | None = None,
    ) -> StoredPlan:
        """Write a reviewed plan atomically, and return what was written."""
        created_at = now or utc_now()
        stored = StoredPlan(
            plan=plan,
            created_at=created_at,
            expires_at=created_at + EXECUTION_WINDOW,
            preview_result=preview_result,
        )
        envelope: dict[str, Any] = {
            "format_version": PLAN_STORE_FORMAT_VERSION,
            "plan_id": plan.plan_id,
            "created_at": stored.created_at.isoformat(),
            "expires_at": stored.expires_at.isoformat(),
            "frozen_plan": plan.model_dump(mode="json"),
        }
        if preview_result is not None:
            envelope["preview_result"] = preview_result
        with self._write_lock:
            try:
                self.review_path_for(plan.plan_id).unlink(missing_ok=True)
            except OSError as exc:
                raise PlanStoreError(
                    f"Could not clear superseded Review state for {plan.plan_id}: {exc}"
                ) from exc
            self._write_json(self.path_for(plan.plan_id), envelope)
            self._known_plans[plan.plan_id] = (plan.config_fingerprint, stored.expires_at)
        return stored

    def save_review_state(
        self,
        plan_id: str,
        review_state: dict[str, Any],
        *,
        expected_config_fingerprint: str,
    ) -> None:
        """Durably replace only Review's state for an existing frozen plan."""
        with self._write_lock:
            known = self._known_plans.get(plan_id)
            if known is None:
                loaded = self.load(plan_id)
                known = (loaded.plan.config_fingerprint, loaded.expires_at)
            fingerprint, expires_at = known
            if utc_now() >= expires_at:
                raise PlanExpiredError(
                    f"the reviewed plan expired at {expires_at.isoformat()}; "
                    "generate and review a new preview."
                )
            if not self.path_for(plan_id).is_file():
                self._known_plans.pop(plan_id, None)
                raise InvalidPlanStoreError(f"no stored plan for {plan_id}")
            if fingerprint != expected_config_fingerprint:
                raise InvalidPlanStoreError(
                    f"stored plan {plan_id} belongs to a different configuration"
                )
            self._write_json(self.review_path_for(plan_id), review_state)

    def load(self, plan_id: str, *, now: datetime | None = None) -> StoredPlan:
        """Return an executable plan, or raise a typed refusal saying why not."""
        path = self.path_for(plan_id)
        if not path.is_file():
            raise InvalidPlanStoreError(f"no stored plan for {plan_id}")

        try:
            raw = path.read_text(encoding="utf-8")
        except OSError as exc:
            raise InvalidPlanStoreError(f"stored plan {plan_id} is unreadable: {exc}") from exc

        try:
            envelope = json.loads(raw)
        except json.JSONDecodeError as exc:
            self._quarantine(path, f"unparseable JSON: {exc}")
            raise InvalidPlanStoreError(f"stored plan {plan_id} is corrupt") from exc
        if not isinstance(envelope, dict):
            self._quarantine(path, "envelope is not an object")
            raise InvalidPlanStoreError(f"stored plan {plan_id} is not an envelope")

        version = envelope.get("format_version")
        if version != PLAN_STORE_FORMAT_VERSION:
            if isinstance(version, int) and version > PLAN_STORE_FORMAT_VERSION:
                raise UnsupportedPlanStoreVersionError(
                    f"stored plan {plan_id} uses format version {version}; this build "
                    f"understands {PLAN_STORE_FORMAT_VERSION}. Generate the preview again."
                )
            self._quarantine(path, f"unusable format_version {version!r}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} has an unusable format_version: {version!r}"
            )

        created_at = _parse_timestamp(envelope.get("created_at"), "created_at")
        expires_at = _parse_timestamp(envelope.get("expires_at"), "expires_at")
        try:
            plan = FrozenSortPlan.model_validate(envelope["frozen_plan"])
        except (KeyError, ValueError) as exc:
            self._quarantine(path, f"frozen_plan did not validate: {exc}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} does not contain a valid plan"
            ) from exc

        if plan.plan_id != plan_id:
            self._quarantine(path, f"envelope names {plan_id} but holds {plan.plan_id}")
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} identifies itself as {plan.plan_id}"
            )

        preview_result = envelope.get("preview_result")
        review_state = self._read_review_state(plan_id, envelope.get("review_state"))
        if preview_result is not None and not isinstance(preview_result, dict):
            raise InvalidPlanStoreError(f"stored plan {plan_id} has an invalid preview result")
        if review_state is not None and not isinstance(review_state, dict):
            raise InvalidPlanStoreError(f"stored plan {plan_id} has an invalid review state")
        stored = StoredPlan(
            plan=plan,
            created_at=created_at,
            expires_at=expires_at,
            preview_result=preview_result,
            review_state=review_state,
        )
        if stored.is_expired(now=now):
            raise PlanExpiredError(
                f"the reviewed plan expired at {expires_at.isoformat()}; "
                "generate and review a new preview."
            )
        self._known_plans[plan_id] = (plan.config_fingerprint, expires_at)
        return stored

    def _read_review_state(self, plan_id: str, embedded: Any) -> dict[str, Any] | None:
        """Prefer the canonical sidecar while accepting an additive legacy field."""
        sidecar = self.review_path_for(plan_id)
        if not sidecar.exists():
            if embedded is not None and not isinstance(embedded, dict):
                raise InvalidPlanStoreError(f"stored plan {plan_id} has an invalid review state")
            return embedded
        try:
            state = json.loads(sidecar.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise InvalidPlanStoreError(
                f"stored plan {plan_id} has unreadable Review state"
            ) from exc
        if not isinstance(state, dict):
            raise InvalidPlanStoreError(f"stored plan {plan_id} has an invalid review state")
        return state

    def _write_json(self, target: Path, value: dict[str, Any]) -> None:
        """Atomically replace one JSON object and make the directory entry durable."""
        self.root.mkdir(parents=True, exist_ok=True)
        temporary = target.with_name(f"{target.name}{TEMP_SUFFIX}")
        payload = json.dumps(value, ensure_ascii=False, indent=2)
        try:
            with temporary.open("w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, target)
            directory = os.open(self.root, os.O_RDONLY)
            try:
                os.fsync(directory)
            finally:
                os.close(directory)
        except OSError as exc:
            temporary.unlink(missing_ok=True)
            raise PlanStoreError(f"Could not persist the reviewed plan: {exc}") from exc

    def purge_expired(self, *, now: datetime | None = None) -> tuple[str, ...]:
        """Remove plans past even the diagnostic window. Explicit, never implicit.

        A `start` never calls this: silently discarding a plan the user is about
        to name would turn an expiry into a "no such plan", which is precisely
        the confusion the typed errors exist to prevent.
        """
        if not self.root.is_dir():
            return ()
        removed: list[str] = []
        for path in sorted(self.root.glob(f"*{PLAN_SUFFIX}")):
            plan_id = path.name[: -len(PLAN_SUFFIX)]
            try:
                envelope = json.loads(path.read_text(encoding="utf-8"))
                expires_at = _parse_timestamp(envelope.get("expires_at"), "expires_at")
            except (OSError, ValueError, json.JSONDecodeError, InvalidPlanStoreError):
                continue
            if (now or utc_now()) >= expires_at + DIAGNOSTIC_RETENTION:
                path.unlink(missing_ok=True)
                self.review_path_for(plan_id).unlink(missing_ok=True)
                self._known_plans.pop(plan_id, None)
                removed.append(plan_id)
        return tuple(removed)

    def _quarantine(self, path: Path, reason: str) -> None:
        """Move an unreadable plan aside. It is evidence, not litter."""
        try:
            self.quarantine_root.mkdir(parents=True, exist_ok=True)
            shutil.move(str(path), str(self.quarantine_root / path.name))
        except OSError:  # pragma: no cover - best effort, never the caller's problem
            logger.warning("plan_store.quarantine_failed", path=str(path), reason=reason)
            return
        logger.warning("plan_store.quarantined", path=str(path), reason=reason)


def store_for_state_root(state_root: Path) -> PlanStore:
    """Plans live beside the journals that record acting on them."""
    return PlanStore(state_root / PLAN_DIRECTORY_NAME)
